### PR TITLE
Updating gradle version and dependecies

### PR DESCRIPTION
**Pull request by mmaietta**

### CODE REVIEW

**Comment by mmaietta** [comment]
trigger ci build

**Comment by michael-quinlan** [comment]
Looks good

**Comment by mmaietta** [comment]
trigger ci build

**Comment by mmaietta** [comment]
trigger ci build

**Comment by mmaietta** [comment]
Build triggered. sha1 is merged.

**Comment by mmaietta** [comment]
Build started sha1 is merged.

**Comment by mmaietta** [comment]
Build finished. No test results found.

**Comment by mmaietta** [comment]
trigger ci build

**Comment by mmaietta** [comment]
Build finished. No test results found.

**Pull request merged**
